use phf::{phf_set, Set};

pub const MAX_PACKAGE_NAME_LENGTH: u8 = 214;

pub static BLACK_LIST: Set<&'static str> = phf_set! {
    // https://github.com/npm/validate-npm-package-name/blob/b7753c95bd57b8d087c4e01ee497d2134fa7130c/lib/index.js
    "node_modules",
    "favicon.ico",
    // node.js builtins
    // see https://nodejs.org/api/modules.html#core-modules
    "assert",
    "assert/strict",
    "async_hooks",
    "buffer",
    "child_process",
    "cluster",
    "console",
    "constants",
    "crypto",
    "dgram",
    "diagnostics_channel",
    "dns",
    "dns/promises",
    "domain",
    "events",
    "fs",
    "fs/promises",
    "http",
    "http2",
    "https",
    "inspector",
    "module",
    "net",
    "os",
    "path",
    "path/posix",
    "path/win32",
    "perf_hooks",
    "process",
    "punycode",
    "querystring",
    "readline",
    "repl",
    "stream",
    "stream/consumers",
    "stream/promises",
    "stream/web",
    "string_decoder",
    "sys",
    "timers",
    "timers/promises",
    "tls",
    "trace_events",
    "tty",
    "url",
    "util",
    "util/types",
    "v8",
    "vm",
    "worker_threads",
    "zlib",
};
